// ============================================================
// AI Text Polisher - Background Service Worker
// ============================================================
// Chat, ClickUp-grounded answers, and proposals all run through n8n using
// n8n's own credentials, so the extension holds no AI API key. This worker's
// only jobs are: dispatch the chat-overlay keyboard command, and relay
// chat/proposal requests to the n8n workflow.
// ============================================================

// Keyboard commands:
//   Alt+Shift+O — toggle the chat overlay on the active tab
//   Alt+Shift+H — stealth mode: hide/show the extension UI on ALL tabs
//                 (for Loom / screen recordings). The flag lives in
//                 chrome.storage.local so every tab reacts via onChanged.
chrome.commands.onCommand.addListener((command) => {
  if (command === "toggle-chat") {
    chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
      if (tabs[0]) {
        chrome.tabs.sendMessage(tabs[0].id, { action: "toggle-chat-overlay" });
      }
    });
    return;
  }

  if (command === "toggle-stealth") {
    chrome.storage.local.get("aip_stealth", (r) => {
      chrome.storage.local.set({ aip_stealth: !(r && r.aip_stealth) });
    });
  }
});

// Message router — chat + proposals, both answered by n8n
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.action === "chat-api") {
    callChatAPI(message.messages, message.useClickup)
      .then(result => sendResponse({ success: true, text: result }))
      .catch(error => sendResponse({ success: false, error: error.message }));
    return true;
  }

  if (message.action === "n8n-proposal") {
    callN8nProposalBot(message.text, message.winningProposals, message.model, message.loom)
      .then(result => sendResponse({ success: true, text: result }))
      .catch(error => sendResponse({ success: false, error: error.message }));
    return true;
  }
});

// ============================================================
// Chat API — answered entirely by n8n (n8n's own Anthropic/OpenAI credentials)
// ------------------------------------------------------------
// All in-page overlay + popup chat is generated by the n8n workflow, so the
// extension needs NO API key. The workflow's "chat" branch builds the persona
// prompt, optionally injects live ClickUp tasks (when useClickup is on), and
// runs the AI Agent with n8n's stored credentials.
// ============================================================

// Flatten the Claude-style messages[] into a plain-text transcript for n8n,
// which has no conversation-memory node. Attachments can't cross the webhook,
// so they become short placeholders — chat still works, minus the file.
function messagesToTranscript(messages) {
  return (Array.isArray(messages) ? messages : []).slice(-20).map((m) => {
    const who = m.role === "assistant" ? "Assistant" : "User";
    let text = "";
    if (typeof m.content === "string") {
      text = m.content;
    } else if (Array.isArray(m.content)) {
      text = m.content.map((block) => {
        if (block.type === "text") return block.text;
        if (block.type === "image") return "[image attachment omitted]";
        if (block.type === "document") return "[PDF attachment omitted]";
        return "";
      }).filter(Boolean).join("\n");
    }
    return `${who}: ${text.slice(0, 20000)}`;
  }).join("\n\n");
}

// Chat API — multi-turn conversation, generated inside n8n.
async function callChatAPI(messages, useClickup = false) {
  const { customPrompt, clickupContextEnabled, n8nWebhookUrl, proposalModel } = await chrome.storage.sync.get([
    "customPrompt", "clickupContextEnabled", "n8nWebhookUrl", "proposalModel"
  ]);

  if (!n8nWebhookUrl) {
    throw new Error("n8n webhook URL not set. Go to the Settings tab and paste your n8n chat webhook URL.");
  }

  // ClickUp grounding is on for this turn if the overlay's history button asked
  // for it (useClickup) or the global toggle is on (clickupContextEnabled).
  const clickupOn = useClickup === true || clickupContextEnabled === true;

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 45000);

  let response;
  try {
    response = await fetch(n8nWebhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        action: "sendMessage",
        mode: "chat",
        useClickup: clickupOn,
        chatInput: messagesToTranscript(messages),
        customPrompt: (customPrompt || "").slice(0, 8000),
        model: proposalModel === "chatgpt" ? "chatgpt" : "claude",
        sessionId: "ext-chat-" + Date.now()
      }),
      signal: controller.signal
    });
  } catch (error) {
    if (error.name === "AbortError") {
      throw new Error("n8n chat timed out after 45 seconds.");
    }
    throw error;
  } finally {
    clearTimeout(timeoutId);
  }

  if (!response.ok) {
    const errorBody = await response.text().catch(() => "");
    throw new Error(errorBody || `n8n error: ${response.status}`);
  }

  const data = await response.json().catch(() => ({}));
  const text = (data.output || data.text || "").toString().trim();
  if (!text) {
    throw new Error("n8n returned an empty response. Check the workflow's chat branch.");
  }
  return text;
}

// n8n Proposal Bot API
// loom=true asks the workflow's Build Prompt node (mode:"loom") for a Loom
// package: spoken video script + examples to show + short proposal to send
// with the Loom link. Regular proposals send NO mode field — the workflow's
// router treats "no mode" and "loom" both as the proposal branch.
async function callN8nProposalBot(jobDescription, winningProposals, model, loom) {
  const { n8nWebhookUrl, proposalModel } = await chrome.storage.sync.get(["n8nWebhookUrl", "proposalModel"]);

  if (!n8nWebhookUrl) {
    throw new Error("n8n webhook URL not set. Go to Settings tab.");
  }

  const response = await fetch(n8nWebhookUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      action: "sendMessage",
      ...(loom === true ? { mode: "loom" } : {}),
      chatInput: jobDescription,
      winningProposals: Array.isArray(winningProposals) ? winningProposals : [],
      model: model || proposalModel || "claude",
      sessionId: "ext-" + Date.now()
    })
  });

  if (!response.ok) {
    throw new Error(`n8n error: ${response.status}`);
  }

  const data = await response.json();
  return data.output || data.text || JSON.stringify(data);
}
